#!/usr/bin/env python

from machinelearning import mlgraph, examples, logisticregression

# Load the dataset, last column is the answer
data = examples.examples('../courses/ml-006/mlclass-ex2/ex2data1.txt')

#g = mlgraph.mlgraph()
#g.scatter('Exams', data.getX('train'), data.getY('train'), ['Exam 1 score', 'Exam 2 score'])
#g.show()

lr = logisticregression.logisticregression()
theta = [[1], [0], [1], [0]] 			# [1 0 1 0]'
X = [[8,1,6], [3,5,7], [4,9,2]]		    # magic(3)
hox = [[0.88080], [0.99753], [0.99995]]
y = [[1], [1], [1]]                     # [1 1 1]'
optimalTheta = lr.optimiseParameters(X, y)
print optimalTheta


# A * B 				# Matrix multiply (when both are numpy matrices, use 'A = numpy.mat(A)' to recast)
#numpy.multiply(A, B)	# Element-wise multiply